files:
  - source: /morphic-community-webapp/en.json
    translation: /morphic-community-webapp/%two_letters_code%.json
  - source: /morphic-windows/Morphic.Client/Properties/Resources.resx
    translation: /morphic-windows/Morphic.Client/Properties/Resources.%two_letters_code%.resx
